name: CI

on:
  push:
    paths-ignore:
    - 'docs/**'
    - '*.md'
  pull_request:
    paths-ignore:
    - 'docs/**'
    - '*.md'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: macos-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    # Builds kotlin project and runs unit tests
    - name: Run unit tests
      run: ./gradlew build check
